---
apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: fraud.miloapis.com-fraudevaluation
spec:
  serviceRef:
    name: "fraud.miloapis.com"
  kind: FraudEvaluation
  plural: fraudevaluations
  singular: fraudevaluation
  subresources:
    - name: status
      permissions:
        - get
        - update
        - patch
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
