---
apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: fraud.miloapis.com-fraudprovider
spec:
  serviceRef:
    name: "fraud.miloapis.com"
  kind: FraudProvider
  plural: fraudproviders
  singular: fraudprovider
  subresources:
    - name: status
      permissions:
        - get
        - update
        - patch
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
